package com.keylesson.persistence;
// Generated Jan 25, 2018 5:53:43 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = -3971327585968655254L;
	
	private int id;
	private String name;
	private Double price;
	private Set<Category> categories = new HashSet<Category>(0);

	public Product() {
	}

	public Product(String name) {
		this.name = name;
	}

	public Product(String name, Double price, Set<Category> categories) {
		this.name = name;
		this.price = price;
		this.categories = categories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

}
