package com.keylesson.persistence;
// Generated Jan 25, 2018 5:53:43 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = -6107010955253381193L;
	
	private int id;
	private Country country;
	private String login;
	private String name;
	private Integer age;
	private String phone;
	private String email;
	private String password;
	private Set<Purchase> purchases = new HashSet<Purchase>(0);

	public User() {
	}

	public User(int id, String login, String name, String email, String password) {
		this.id = id;
		this.login = login;
		this.name = name;
		this.email = email;
		this.password = password;
	}

	public User(int id, Country country, String login, String name, Integer age, String phone, String email, String password, Set<Purchase> purchases) {
		this.id = id;
		this.country = country;
		this.login = login;
		this.name = name;
		this.age = age;
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.purchases = purchases;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Purchase> getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set<Purchase> purchases) {
		this.purchases = purchases;
	}

}
